package drift

// commonAzureOperations is a representative catalogue of Azure
// resource-manager operations covering the resource providers most
// commonly referenced in RBAC roles. It is NOT exhaustive — the true
// Azure catalogue contains thousands of operations across hundreds
// of providers — but it is broad enough to make wildcard expansion
// meaningful for the drift analyzer.
//
// When a role grants `Microsoft.Compute/*`, ExpandActions walks this
// list and keeps every operation whose string matches the pattern.
// The list is deliberately ordered provider-by-provider so that a
// grep against it is easy to audit.
var commonAzureOperations = []string{
	// ---------- Microsoft.Authorization ----------
	"Microsoft.Authorization/roleAssignments/read",
	"Microsoft.Authorization/roleAssignments/write",
	"Microsoft.Authorization/roleAssignments/delete",
	"Microsoft.Authorization/roleDefinitions/read",
	"Microsoft.Authorization/roleDefinitions/write",
	"Microsoft.Authorization/roleDefinitions/delete",
	"Microsoft.Authorization/policyAssignments/read",
	"Microsoft.Authorization/policyAssignments/write",
	"Microsoft.Authorization/policyAssignments/delete",
	"Microsoft.Authorization/policyDefinitions/read",
	"Microsoft.Authorization/policyDefinitions/write",
	"Microsoft.Authorization/policyDefinitions/delete",
	"Microsoft.Authorization/policySetDefinitions/read",
	"Microsoft.Authorization/policySetDefinitions/write",
	"Microsoft.Authorization/policySetDefinitions/delete",
	"Microsoft.Authorization/policyExemptions/read",
	"Microsoft.Authorization/policyExemptions/write",
	"Microsoft.Authorization/policyExemptions/delete",
	"Microsoft.Authorization/locks/read",
	"Microsoft.Authorization/locks/write",
	"Microsoft.Authorization/locks/delete",
	"Microsoft.Authorization/elevateAccess/Action",

	// ---------- Microsoft.Compute ----------
	"Microsoft.Compute/virtualMachines/read",
	"Microsoft.Compute/virtualMachines/write",
	"Microsoft.Compute/virtualMachines/delete",
	"Microsoft.Compute/virtualMachines/start/action",
	"Microsoft.Compute/virtualMachines/powerOff/action",
	"Microsoft.Compute/virtualMachines/restart/action",
	"Microsoft.Compute/virtualMachines/deallocate/action",
	"Microsoft.Compute/virtualMachines/redeploy/action",
	"Microsoft.Compute/virtualMachines/runCommand/action",
	"Microsoft.Compute/virtualMachines/runCommands/read",
	"Microsoft.Compute/virtualMachines/runCommands/write",
	"Microsoft.Compute/virtualMachines/runCommands/delete",
	"Microsoft.Compute/virtualMachines/extensions/read",
	"Microsoft.Compute/virtualMachines/extensions/write",
	"Microsoft.Compute/virtualMachines/extensions/delete",
	"Microsoft.Compute/virtualMachines/instanceView/read",
	"Microsoft.Compute/virtualMachines/login/action",
	"Microsoft.Compute/virtualMachines/loginAsAdmin/action",
	"Microsoft.Compute/virtualMachineScaleSets/read",
	"Microsoft.Compute/virtualMachineScaleSets/write",
	"Microsoft.Compute/virtualMachineScaleSets/delete",
	"Microsoft.Compute/virtualMachineScaleSets/start/action",
	"Microsoft.Compute/virtualMachineScaleSets/powerOff/action",
	"Microsoft.Compute/virtualMachineScaleSets/virtualMachines/read",
	"Microsoft.Compute/virtualMachineScaleSets/virtualMachines/write",
	"Microsoft.Compute/virtualMachineScaleSets/virtualMachines/login/action",
	"Microsoft.Compute/virtualMachineScaleSets/virtualMachines/loginAsAdmin/action",
	"Microsoft.Compute/disks/read",
	"Microsoft.Compute/disks/write",
	"Microsoft.Compute/disks/delete",
	"Microsoft.Compute/disks/beginGetAccess/action",
	"Microsoft.Compute/disks/endGetAccess/action",
	"Microsoft.Compute/snapshots/read",
	"Microsoft.Compute/snapshots/write",
	"Microsoft.Compute/snapshots/delete",
	"Microsoft.Compute/images/read",
	"Microsoft.Compute/images/write",
	"Microsoft.Compute/images/delete",
	"Microsoft.Compute/galleries/read",
	"Microsoft.Compute/galleries/write",
	"Microsoft.Compute/galleries/delete",
	"Microsoft.Compute/galleries/share/action",
	"Microsoft.Compute/availabilitySets/read",
	"Microsoft.Compute/availabilitySets/write",
	"Microsoft.Compute/availabilitySets/delete",
	"Microsoft.Compute/locations/usages/read",
	"Microsoft.Compute/locations/vmSizes/read",

	// ---------- Microsoft.Network ----------
	"Microsoft.Network/virtualNetworks/read",
	"Microsoft.Network/virtualNetworks/write",
	"Microsoft.Network/virtualNetworks/delete",
	"Microsoft.Network/virtualNetworks/peer/action",
	"Microsoft.Network/virtualNetworks/join/action",
	"Microsoft.Network/virtualNetworks/subnets/read",
	"Microsoft.Network/virtualNetworks/subnets/write",
	"Microsoft.Network/virtualNetworks/subnets/delete",
	"Microsoft.Network/virtualNetworks/subnets/join/action",
	"Microsoft.Network/virtualNetworks/subnets/joinViaServiceEndpoint/action",
	"Microsoft.Network/virtualNetworks/virtualNetworkPeerings/read",
	"Microsoft.Network/virtualNetworks/virtualNetworkPeerings/write",
	"Microsoft.Network/virtualNetworks/virtualNetworkPeerings/delete",
	"Microsoft.Network/networkInterfaces/read",
	"Microsoft.Network/networkInterfaces/write",
	"Microsoft.Network/networkInterfaces/delete",
	"Microsoft.Network/networkInterfaces/join/action",
	"Microsoft.Network/networkInterfaces/effectiveRouteTable/action",
	"Microsoft.Network/networkInterfaces/effectiveNetworkSecurityGroups/action",
	"Microsoft.Network/networkSecurityGroups/read",
	"Microsoft.Network/networkSecurityGroups/write",
	"Microsoft.Network/networkSecurityGroups/delete",
	"Microsoft.Network/networkSecurityGroups/join/action",
	"Microsoft.Network/networkSecurityGroups/securityRules/read",
	"Microsoft.Network/networkSecurityGroups/securityRules/write",
	"Microsoft.Network/networkSecurityGroups/securityRules/delete",
	"Microsoft.Network/publicIPAddresses/read",
	"Microsoft.Network/publicIPAddresses/write",
	"Microsoft.Network/publicIPAddresses/delete",
	"Microsoft.Network/publicIPAddresses/join/action",
	"Microsoft.Network/loadBalancers/read",
	"Microsoft.Network/loadBalancers/write",
	"Microsoft.Network/loadBalancers/delete",
	"Microsoft.Network/loadBalancers/backendAddressPools/join/action",
	"Microsoft.Network/loadBalancers/inboundNatRules/join/action",
	"Microsoft.Network/applicationGateways/read",
	"Microsoft.Network/applicationGateways/write",
	"Microsoft.Network/applicationGateways/delete",
	"Microsoft.Network/applicationGateways/start/action",
	"Microsoft.Network/applicationGateways/stop/action",
	"Microsoft.Network/applicationGateways/backendAddressPools/join/action",
	"Microsoft.Network/routeTables/read",
	"Microsoft.Network/routeTables/write",
	"Microsoft.Network/routeTables/delete",
	"Microsoft.Network/routeTables/join/action",
	"Microsoft.Network/routeTables/routes/read",
	"Microsoft.Network/routeTables/routes/write",
	"Microsoft.Network/routeTables/routes/delete",
	"Microsoft.Network/virtualNetworkGateways/read",
	"Microsoft.Network/virtualNetworkGateways/write",
	"Microsoft.Network/virtualNetworkGateways/delete",
	"Microsoft.Network/firewallPolicies/read",
	"Microsoft.Network/firewallPolicies/write",
	"Microsoft.Network/firewallPolicies/delete",
	"Microsoft.Network/azureFirewalls/read",
	"Microsoft.Network/azureFirewalls/write",
	"Microsoft.Network/azureFirewalls/delete",
	"Microsoft.Network/privateEndpoints/read",
	"Microsoft.Network/privateEndpoints/write",
	"Microsoft.Network/privateEndpoints/delete",
	"Microsoft.Network/privateDnsZones/read",
	"Microsoft.Network/privateDnsZones/write",
	"Microsoft.Network/privateDnsZones/delete",
	"Microsoft.Network/dnsZones/read",
	"Microsoft.Network/dnsZones/write",
	"Microsoft.Network/dnsZones/delete",
	"Microsoft.Network/locations/operationResults/read",

	// ---------- Microsoft.Storage ----------
	"Microsoft.Storage/storageAccounts/read",
	"Microsoft.Storage/storageAccounts/write",
	"Microsoft.Storage/storageAccounts/delete",
	"Microsoft.Storage/storageAccounts/listKeys/action",
	"Microsoft.Storage/storageAccounts/regenerateKey/action",
	"Microsoft.Storage/storageAccounts/listAccountSas/action",
	"Microsoft.Storage/storageAccounts/listServiceSas/action",
	"Microsoft.Storage/storageAccounts/rotateKey/action",
	"Microsoft.Storage/storageAccounts/failover/action",
	"Microsoft.Storage/storageAccounts/blobServices/read",
	"Microsoft.Storage/storageAccounts/blobServices/write",
	"Microsoft.Storage/storageAccounts/blobServices/generateUserDelegationKey/action",
	"Microsoft.Storage/storageAccounts/blobServices/containers/read",
	"Microsoft.Storage/storageAccounts/blobServices/containers/write",
	"Microsoft.Storage/storageAccounts/blobServices/containers/delete",
	"Microsoft.Storage/storageAccounts/blobServices/containers/lease/action",
	"Microsoft.Storage/storageAccounts/blobServices/containers/blobs/read",
	"Microsoft.Storage/storageAccounts/blobServices/containers/blobs/write",
	"Microsoft.Storage/storageAccounts/blobServices/containers/blobs/delete",
	"Microsoft.Storage/storageAccounts/blobServices/containers/blobs/move/action",
	"Microsoft.Storage/storageAccounts/blobServices/containers/blobs/add/action",
	"Microsoft.Storage/storageAccounts/fileServices/read",
	"Microsoft.Storage/storageAccounts/fileServices/write",
	"Microsoft.Storage/storageAccounts/fileServices/shares/read",
	"Microsoft.Storage/storageAccounts/fileServices/shares/write",
	"Microsoft.Storage/storageAccounts/fileServices/shares/delete",
	"Microsoft.Storage/storageAccounts/fileServices/fileshares/files/read",
	"Microsoft.Storage/storageAccounts/fileServices/fileshares/files/write",
	"Microsoft.Storage/storageAccounts/fileServices/fileshares/files/delete",
	"Microsoft.Storage/storageAccounts/queueServices/read",
	"Microsoft.Storage/storageAccounts/queueServices/write",
	"Microsoft.Storage/storageAccounts/queueServices/queues/read",
	"Microsoft.Storage/storageAccounts/queueServices/queues/write",
	"Microsoft.Storage/storageAccounts/queueServices/queues/delete",
	"Microsoft.Storage/storageAccounts/queueServices/queues/messages/read",
	"Microsoft.Storage/storageAccounts/queueServices/queues/messages/write",
	"Microsoft.Storage/storageAccounts/queueServices/queues/messages/delete",
	"Microsoft.Storage/storageAccounts/tableServices/read",
	"Microsoft.Storage/storageAccounts/tableServices/write",
	"Microsoft.Storage/storageAccounts/tableServices/tables/read",
	"Microsoft.Storage/storageAccounts/tableServices/tables/write",
	"Microsoft.Storage/storageAccounts/tableServices/tables/delete",
	"Microsoft.Storage/storageAccounts/tableServices/tables/entities/read",
	"Microsoft.Storage/storageAccounts/tableServices/tables/entities/write",
	"Microsoft.Storage/storageAccounts/tableServices/tables/entities/delete",

	// ---------- Microsoft.KeyVault ----------
	"Microsoft.KeyVault/vaults/read",
	"Microsoft.KeyVault/vaults/write",
	"Microsoft.KeyVault/vaults/delete",
	"Microsoft.KeyVault/vaults/deploy/action",
	"Microsoft.KeyVault/vaults/accessPolicies/write",
	"Microsoft.KeyVault/vaults/keys/read",
	"Microsoft.KeyVault/vaults/keys/write",
	"Microsoft.KeyVault/vaults/keys/delete",
	"Microsoft.KeyVault/vaults/keys/backup/action",
	"Microsoft.KeyVault/vaults/keys/restore/action",
	"Microsoft.KeyVault/vaults/secrets/read",
	"Microsoft.KeyVault/vaults/secrets/write",
	"Microsoft.KeyVault/vaults/secrets/delete",
	"Microsoft.KeyVault/vaults/secrets/getSecret/action",
	"Microsoft.KeyVault/vaults/secrets/readMetadata/action",
	"Microsoft.KeyVault/vaults/certificates/read",
	"Microsoft.KeyVault/vaults/certificates/write",
	"Microsoft.KeyVault/vaults/certificates/delete",
	"Microsoft.KeyVault/vaults/certificatecontacts/read",
	"Microsoft.KeyVault/vaults/certificatecontacts/write",
	"Microsoft.KeyVault/locations/deletedVaults/read",
	"Microsoft.KeyVault/locations/deletedVaults/purge/action",
	"Microsoft.KeyVault/checkNameAvailability/read",

	// ---------- Microsoft.Sql ----------
	"Microsoft.Sql/servers/read",
	"Microsoft.Sql/servers/write",
	"Microsoft.Sql/servers/delete",
	"Microsoft.Sql/servers/databases/read",
	"Microsoft.Sql/servers/databases/write",
	"Microsoft.Sql/servers/databases/delete",
	"Microsoft.Sql/servers/databases/pause/action",
	"Microsoft.Sql/servers/databases/resume/action",
	"Microsoft.Sql/servers/databases/export/action",
	"Microsoft.Sql/servers/databases/import/action",
	"Microsoft.Sql/servers/databases/auditingSettings/read",
	"Microsoft.Sql/servers/databases/auditingSettings/write",
	"Microsoft.Sql/servers/databases/securityAlertPolicies/read",
	"Microsoft.Sql/servers/databases/securityAlertPolicies/write",
	"Microsoft.Sql/servers/databases/transparentDataEncryption/read",
	"Microsoft.Sql/servers/databases/transparentDataEncryption/write",
	"Microsoft.Sql/servers/firewallRules/read",
	"Microsoft.Sql/servers/firewallRules/write",
	"Microsoft.Sql/servers/firewallRules/delete",
	"Microsoft.Sql/servers/administrators/read",
	"Microsoft.Sql/servers/administrators/write",
	"Microsoft.Sql/locations/capabilities/read",

	// ---------- Microsoft.Web ----------
	"Microsoft.Web/sites/read",
	"Microsoft.Web/sites/write",
	"Microsoft.Web/sites/delete",
	"Microsoft.Web/sites/start/action",
	"Microsoft.Web/sites/stop/action",
	"Microsoft.Web/sites/restart/action",
	"Microsoft.Web/sites/publish/action",
	"Microsoft.Web/sites/config/read",
	"Microsoft.Web/sites/config/write",
	"Microsoft.Web/sites/config/list/action",
	"Microsoft.Web/sites/publishxml/action",
	"Microsoft.Web/sites/publishingcredentials/list/action",
	"Microsoft.Web/sites/host/listkeys/action",
	"Microsoft.Web/sites/functions/read",
	"Microsoft.Web/sites/functions/write",
	"Microsoft.Web/sites/functions/delete",
	"Microsoft.Web/sites/functions/listkeys/action",
	"Microsoft.Web/sites/slots/read",
	"Microsoft.Web/sites/slots/write",
	"Microsoft.Web/sites/slots/delete",
	"Microsoft.Web/sites/slots/start/action",
	"Microsoft.Web/sites/slots/stop/action",
	"Microsoft.Web/sites/slots/swap/action",
	"Microsoft.Web/serverfarms/read",
	"Microsoft.Web/serverfarms/write",
	"Microsoft.Web/serverfarms/delete",
	"Microsoft.Web/certificates/read",
	"Microsoft.Web/certificates/write",
	"Microsoft.Web/certificates/delete",

	// ---------- Microsoft.Resources ----------
	"Microsoft.Resources/subscriptions/read",
	"Microsoft.Resources/subscriptions/resourceGroups/read",
	"Microsoft.Resources/subscriptions/resourceGroups/write",
	"Microsoft.Resources/subscriptions/resourceGroups/delete",
	"Microsoft.Resources/deployments/read",
	"Microsoft.Resources/deployments/write",
	"Microsoft.Resources/deployments/delete",
	"Microsoft.Resources/deployments/validate/action",
	"Microsoft.Resources/deployments/cancel/action",
	"Microsoft.Resources/deployments/whatIf/action",
	"Microsoft.Resources/tags/read",
	"Microsoft.Resources/tags/write",
	"Microsoft.Resources/tags/delete",

	// ---------- Microsoft.Security ----------
	"Microsoft.Security/alerts/read",
	"Microsoft.Security/alerts/dismiss/action",
	"Microsoft.Security/alerts/activate/action",
	"Microsoft.Security/assessments/read",
	"Microsoft.Security/assessments/write",
	"Microsoft.Security/assessments/delete",
	"Microsoft.Security/pricings/read",
	"Microsoft.Security/pricings/write",
	"Microsoft.Security/securityContacts/read",
	"Microsoft.Security/securityContacts/write",
	"Microsoft.Security/securityContacts/delete",
	"Microsoft.Security/autoProvisioningSettings/read",
	"Microsoft.Security/autoProvisioningSettings/write",
	"Microsoft.Security/policies/read",
	"Microsoft.Security/policies/write",
	"Microsoft.Security/settings/read",
	"Microsoft.Security/settings/write",
	"Microsoft.Security/workspaceSettings/read",
	"Microsoft.Security/workspaceSettings/write",

	// ---------- Microsoft.Insights / Monitoring ----------
	"Microsoft.Insights/alertRules/read",
	"Microsoft.Insights/alertRules/write",
	"Microsoft.Insights/alertRules/delete",
	"Microsoft.Insights/metricAlerts/read",
	"Microsoft.Insights/metricAlerts/write",
	"Microsoft.Insights/metricAlerts/delete",
	"Microsoft.Insights/activityLogAlerts/read",
	"Microsoft.Insights/activityLogAlerts/write",
	"Microsoft.Insights/activityLogAlerts/delete",
	"Microsoft.Insights/actionGroups/read",
	"Microsoft.Insights/actionGroups/write",
	"Microsoft.Insights/actionGroups/delete",
	"Microsoft.Insights/diagnosticSettings/read",
	"Microsoft.Insights/diagnosticSettings/write",
	"Microsoft.Insights/diagnosticSettings/delete",
	"Microsoft.Insights/metrics/read",
	"Microsoft.Insights/metricDefinitions/read",
	"Microsoft.Insights/logDefinitions/read",
	"Microsoft.Insights/eventtypes/values/read",
	"Microsoft.Insights/components/read",
	"Microsoft.Insights/components/write",
	"Microsoft.Insights/components/delete",
	"Microsoft.Insights/webtests/read",
	"Microsoft.Insights/webtests/write",
	"Microsoft.Insights/workbooks/read",
	"Microsoft.Insights/workbooks/write",
	"Microsoft.Insights/workbooks/delete",
	"Microsoft.OperationalInsights/workspaces/read",
	"Microsoft.OperationalInsights/workspaces/write",
	"Microsoft.OperationalInsights/workspaces/delete",
	"Microsoft.OperationalInsights/workspaces/search/action",
	"Microsoft.OperationalInsights/workspaces/sharedKeys/action",
	"Microsoft.OperationalInsights/workspaces/query/read",
	"Microsoft.OperationalInsights/workspaces/savedSearches/read",
	"Microsoft.OperationalInsights/workspaces/savedSearches/write",
	"Microsoft.OperationalInsights/workspaces/analytics/query/action",

	// ---------- Microsoft.ContainerService (AKS) ----------
	"Microsoft.ContainerService/managedClusters/read",
	"Microsoft.ContainerService/managedClusters/write",
	"Microsoft.ContainerService/managedClusters/delete",
	"Microsoft.ContainerService/managedClusters/listClusterAdminCredential/action",
	"Microsoft.ContainerService/managedClusters/listClusterUserCredential/action",
	"Microsoft.ContainerService/managedClusters/listClusterMonitoringUserCredential/action",
	"Microsoft.ContainerService/managedClusters/runcommand/action",
	"Microsoft.ContainerService/managedclusters/commandResults/read",
	"Microsoft.ContainerService/managedClusters/rotateClusterCertificates/action",
	"Microsoft.ContainerService/managedClusters/start/action",
	"Microsoft.ContainerService/managedClusters/stop/action",
	"Microsoft.ContainerService/managedClusters/agentPools/read",
	"Microsoft.ContainerService/managedClusters/agentPools/write",
	"Microsoft.ContainerService/managedClusters/agentPools/delete",
	"Microsoft.ContainerService/managedClusters/upgradeProfiles/read",

	// ---------- Microsoft.RecoveryServices ----------
	"Microsoft.RecoveryServices/Vaults/read",
	"Microsoft.RecoveryServices/Vaults/write",
	"Microsoft.RecoveryServices/Vaults/delete",
	"Microsoft.RecoveryServices/Vaults/backupJobs/read",
	"Microsoft.RecoveryServices/Vaults/backupJobs/cancel/action",
	"Microsoft.RecoveryServices/Vaults/backupPolicies/read",
	"Microsoft.RecoveryServices/Vaults/backupPolicies/write",
	"Microsoft.RecoveryServices/Vaults/backupPolicies/delete",
	"Microsoft.RecoveryServices/Vaults/backupProtectedItems/read",
	"Microsoft.RecoveryServices/Vaults/backupProtectedItems/write",
	"Microsoft.RecoveryServices/Vaults/backupProtectedItems/delete",
	"Microsoft.RecoveryServices/Vaults/backupFabrics/protectionContainers/read",

	// ---------- Microsoft.CostManagement / Billing ----------
	"Microsoft.CostManagement/query/read",
	"Microsoft.CostManagement/exports/read",
	"Microsoft.CostManagement/exports/write",
	"Microsoft.CostManagement/budgets/read",
	"Microsoft.CostManagement/budgets/write",
	"Microsoft.Billing/billingPeriods/read",
	"Microsoft.Consumption/usageDetails/read",
	"Microsoft.Consumption/budgets/read",

	// ---------- Microsoft.Support ----------
	"Microsoft.Support/supportTickets/read",
	"Microsoft.Support/supportTickets/write",
	"Microsoft.Support/services/read",
}
